// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"product-service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/product/get",
				Handler: GetProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/list",
				Handler: ListProductsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/search",
				Handler: SearchProductHandler(serverCtx),
			},
		},
	)
}
