// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: token.proto

package server

import (
	"context"

	"auth-service/auth"
	"auth-service/internal/logic"
	"auth-service/internal/svc"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) DeliverTokenByRPC(ctx context.Context, in *auth.DeliverTokenReq) (*auth.DeliveryResp, error) {
	l := logic.NewDeliverTokenByRPCLogic(ctx, s.svcCtx)
	return l.DeliverTokenByRPC(in)
}

func (s *AuthServiceServer) VerifyTokenByRPC(ctx context.Context, in *auth.VerifyTokenReq) (*auth.VerifyResp, error) {
	l := logic.NewVerifyTokenByRPCLogic(ctx, s.svcCtx)
	return l.VerifyTokenByRPC(in)
}
