Etcd:
  Hosts:
  - 127.0.0.1:2379
  DialTimeout: 5
Port: 8080
Routes:
  - ServiceName: user-api 
    Path:
      - /api/user/login
      - /api/user/register
  - ServiceName: product-api
    Path:
      - /api/product/list
      - /api/product/get
  - ServiceName: cart-api
    Path:
      - /api/cart/addItem
      - /api/cart/emptyCart
      - /api/cart/getCart
        