Name: Product
Host: 0.0.0.0
Port: 8888
db:
  dsn: "root:123456@tcp(127.0.0.1:3306)/gomall?charset=utf8mb4&parseTime=True&loc=Local"
  connectTimeout: 10
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product-api
  DialTimeout: 5
RedisConfig:
  Host: "127.0.0.1:6379"
  Type: "node"
  NonBlock: false
  Tls: false
  PingTimeout: 1s
RedisPrefix: "gomall-product:"