// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddIemResp struct {
	Message string `json:"message"`
}

type AddItemReq struct {
	User_id uint32  `json:"user_id"`
	Item    CartItm `json:"item"`
}

type Cart struct {
	User_id uint32    `json:"user_id"`
	Items   []CartItm `json:"items"`
}

type CartItm struct {
	Product_id uint32 `json:"product_id"`
	Quantity   uint32 `json:"quantity"`
}

type EmptyCartReq struct {
	User_id uint32 `json:"user_id"`
}

type EmptyCartResp struct {
	Message string `json:"message"`
}

type GetCartReq struct {
	User_id uint32 `json:"user_id"`
}

type GetCartResp struct {
	Cart Cart `json:"cart"`
}
