// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"
	"cart-service/model"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cartItemsFieldNames          = builder.RawFieldNames(&CartItems{})
	cartItemsRows                = strings.Join(cartItemsFieldNames, ",")
	cartItemsRowsExpectAutoSet   = strings.Join(stringx.Remove(cartItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cartItemsRowsWithPlaceHolder = strings.Join(stringx.Remove(cartItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	cartItemsModel interface {
		Insert(ctx context.Context, data *CartItems) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CartItems, error)
		Update(ctx context.Context, data *CartItems) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCartItemsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CartItems struct {
		Id        int64     `db:"id"`
		CartId    int64     `db:"cart_id"`
		ProductId uint32     `db:"product_id"`
		Quantity  int64     `db:"quantity"`
		Price     float32   `db:"price"`
	    CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newCartItemsModel(conn sqlx.SqlConn) *defaultCartItemsModel {
	return &defaultCartItemsModel{
		conn:  conn,
		table: "`cart_items`",
	}
}

func (m *defaultCartItemsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCartItemsModel) FindOne(ctx context.Context, id int64) (*CartItems, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cartItemsRows, m.table)
	var resp CartItems
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartItemsModel) Insert(ctx context.Context, data *CartItems) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, cartItemsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CartId, data.ProductId, data.Quantity, data.Price)
	return ret, err
}

func (m *defaultCartItemsModel) Update(ctx context.Context, data *CartItems) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cartItemsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CartId, data.ProductId, data.Quantity, data.Price, data.CreatedAt, data.Id)
	return err
}

func (m *defaultCartItemsModel) tableName() string {
	return m.table
}
